version: "2"
services:
  backend:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database    
  database:
    container_name: api_database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"